[phases.setup]
    nixpacksArchive = 'b5c1a9915e72a2ac1094433e39ce707a755b156b'
    cmds = [
        "curl -fsSL https://bun.sh/install | BUN_INSTALL=/usr/local bash",
        "ln -sf /usr/local/bin/bun /usr/bin/bun"
    ]

[phases.install]
    cmds = ["bun install"]

[start]
    cmd = "bun main.ts"